# Default colorss
[colors.primary]
  background = '#121212'
  foreground = '#F9F9F9'

[colors.cursor]
  text = '#F9F9F9'
  cursor = '#BFBFBF'

# Normal colorss
[colors.normal]
  black =   '#232323'
  red =     '#FF5454'
  green =   '#00CC7A'
  yellow =  '#FFD700'
  blue =    '#00bFFF'
  magenta = '#FF00FF'
  cyan =    '#48d1cc'
  white =   '#bfbfbf'

# Bright colorss
[colors.bright]
  black =   '#767c77'
  red =     '#ff1a75'
  green =   '#1affa3'
  yellow =  '#ffff00'
  blue =    '#28c9ff'
  magenta = '#ff33ff'
  cyan =    '#09fff2'
  white =   '#f9f9f9'
